openapi: 3.0.0
info:
  title: Dummy API
  version: 2.0.0
paths:
  /welcome:
    get:
      summary: Welcome endpoint (renamed from /greeting)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  minor:
                    type: string
                  extra:
                    type: string
  /fail:
    get:
      summary: Fail endpoint (property changed)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /added:
    get:
      summary: Added endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  new:
                    type: string
  /salute:
    get:
      summary: Salute endpoint (renamed from /hello)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
