openapi: 3.0.0
info:
  title: Dummy API
  version: 1.0.0
paths:
  /greeting:
    get:
      summary: Greeting endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  minor:
                    type: string
                  extra:
                    type: string
  /fail:
    get:
      summary: Fail endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
  /added:
    get:
      summary: Added endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  new:
                    type: string
  /hello:
    get:
      summary: Hello endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

