openapi: 3.0.0
info:
  title: Dummy API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a greeting
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  extra:
                    type: integer
  /more:
    post:
      summary: Returns a greeting
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  mee:
                    type: string
  /error:
    get:
      summary: Always returns error
      responses:
        '200':
          description: Should return OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
  /removed:
    get:
      summary: This endpoint will be removed in new spec
      responses:
        '200':
          description: Removed endpoint
          content:
            application/json:
              schema:
                type: object
                properties:
                  gone:
                    type: boolean

